### ISSUE TITLE
Evaluate GitLab Rate Limiting

### ISSUE THREAD

**Issue by cdboer** [DLR-SC/gitlab2prov#12]
To mine many repositories at once, it would help to know if the rate limit is calculated on user basis or on IP basis.

**Comment by cdboer** [comment]
GitLab.com responds with HTTP status code 429 to API requests that exceed 10 requests per second per IP address.
The following example headers are included for all API requests:

RateLimit-Limit: 600
RateLimit-Observed: 6
RateLimit-Remaining: 594
RateLimit-Reset: 1563325137
RateLimit-ResetTime: Wed, 17 Jul 2019 00:58:57 GMT

As found under: https://docs.gitlab.com/ee/user/gitlab_com/index.html#haproxy-api-throttle

For individual instances the following admin panel exists:
https://docs.gitlab.com/ee/user/admin_area/settings/user_and_ip_rate_limits.html

Rate Limits are IP aswell as User based. The API of gitlab.com seems to be using IP based rate limiting, though i can't rule User based limits out as I have not yet tested for them. Self-hosted instances can be unlimited, though for the default case we probably have to assume they aren't.

**Comment by onyame** [comment]
@cdboer rate limit is not set for our internal instance https://gitlab.dlr.de

**Comment by cdboer** [comment]
Good to know. If we want to mine repositories that are hosted on the public instance we should be able to export them to ours and run the mining from there. https://docs.gitlab.com/ee/api/project_import_export.html
It remains to be evaluated whether this works without ownership of the repositories in question and whether this also imports issues aswell as comments and notes on commit ressources.
