### ISSUE TITLE
Code refactorings.

### ISSUE THREAD

**Issue by onyame** [DLR-SC/gitlab2prov#25]
Change code style, conventions, package layout...

**Comment by onyame** [comment]
Many more lint issues, see:
flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

**Comment by cdboer** [comment]
Gonna add flake8 with provided config to my vim configuration. Will help fix warnings over the next few days.

**Comment by cdboer** [comment]
Is it possible to add mypy to the build workflow? We could enforce correct type hints that way.

**Comment by onyame** [comment]
Yes. Please add an additional specific mypy action. 
For example, https://github.com/jpetrucciani/mypy-check?files=1

**Comment by onyame** [comment]
There is a mypy action in the marketplace 

https://github.com/marketplace/actions/mypy-check

**Comment by cdboer** [comment]
Will look into that. :)

**Comment by cdboer** [comment]
This issue will be closed when V1.0 branch is merged into master. Changes in code style, package layout, linting tools, etc will be discussed in seperate issues/merge requests.
