### ISSUE TITLE
Complete command line options

### ISSUE THREAD

**Issue by onyame** [DLR-SC/gitlab2prov#27]
All configuration options that are available in config.ini should be present as command line arguments. 
This is to avoid having an config.ini file.

**Comment by cdboer** [comment]
When implemented, do we want to get rid of the config file completely or do we want to provide the option of having a config file as an alternative to configure gitlab2prov?

**Comment by onyame** [comment]
No, a config file is still useful. It should contain Default values that are overridden by command line options. For example for Auth tokens and Neo4j parameter.

**Comment by cdboer** [comment]
Should values provided by command line flags be written to the config file? Right now they are not.
