### ISSUE TITLE
Recreating the Git2PROV commit model using the GitLab API

### ISSUE THREAD

**Issue by cdboer** [DLR-SC/gitlab2prov#4]
This issue aims to recreate the commit model of #3 that Packer et al. extended in #2.
Resources, data sources and ideas will be posted in the comments.

**Comment by cdboer** [comment]
Python modules:
- gitlab-python: [Python wrapper for the GitLab API ](https://python-gitlab.readthedocs.io/en/stable/index.html)
- prov: [A Python library for W3C Provenance Data Model (PROV)](https://github.com/trungdong/prov)

**Comment by cdboer** [comment]
Data used by #3 to populate the model with its respective PROV translation:
- Commit hash -- activity (commit)
- Parent hash(es) -- derivations
- Author name -- agent (author)
- Author date -- starttime
- Committer name -- agent (committer)
- Committer date -- endtime
- Subject -- prov:label (Commit message)
- name-status -- prov:label (Commit message)

**Comment by cdboer** [comment]
Excerpt from the source of #3

```javascript
 /* We convert git concepts to PROV concepts as follows:
  
  commit c with subject s ---> activity(c, [prov:label="s"])
  file f   ---> entity(f)
  author a ---> agent(a)
               ---> wasAssociatedWith(c, a, [prov:role="author"])
               ---> wasAttributedTo(f_c, a, [prov:type="authorship"])
  committer ca ---> agent(ca)
               ---> wasAssociatedWith(c, ca, [prov:role="committer"])
  author date ad ---> wasStartedBy(c, -, -, ad)
  commit date cd ---> wasEndedBy(c, -, -, cd)
  file f in commit c ---> specializationOf(f_c, f)
  file f_c added in commit c ---> wasGeneratedBy(f_c, c, authordate)
  file f_c in commit c modified f_c2 from parent commit c2 
    ---> wasGeneratedBy(f_c, c, authordate)
    ---> used(c, f_c2, authordate)
    ---> wasDerivedFrom(f_c, f_c2, c)
    ---> wasInformedBy(c, c2)
  file f_c deleted in commit c ---> wasInvalidatedBy(f_c, c, authordate)
*/ 
```

**Comment by cdboer** [comment]
Hey, @onyame  @caha42  I need some input.

The progress thus far allows to generate a PROV document modelled after the Git2PROV model described in #3. 
There are some open questions/issues regarding the modelling of merge requests, but I will adress these later on. 

What is more iportant right now is the following: Performance

Populating the Git2PROV model using only the GitLab API is possible. Apart from the usual commit data, we also need the files that are used in each commit. The GitLab API does not include these in the response to commit GET requests. Rather we can get these by asking for the diff of a commit. Which is fine. Problem is, this has to be done for each commit. The python-gitlab package only allows for synchronous requests and provides no option to query in bulk. At least for diffs. This results in quite a big bottleneck as we have to wait for each diff GET request to resume. And as we have to post as many requests as there are commits in the repository, this can take some time. Especially for bigger repositories. 

Example 
```
# repository of 20.000 commits
n_commits = 20000
avg_response_time = 0.3 # seconds
n_commits * avg_response_time = 6000 # seconds or 100 minutes
```
One way to circumvent this is to post the requests asynchronously. This does have some drawbacks though. For one, if the queried GitLab Instance has set a rate limit, limiting the amount of requests it will answer in a certain time frame, programm progress could be staggered or in fact halted. Also, this would somewhat impact the cleanliness of communication with the GitLab Instance, as we would send simple GET requests with authentification information in the header. Before authentification and session management has been wrapped by the python-gitlab package. Though the actual implementation does not differ from sending an authentification header. The implementation of asynchronousy would be a bit hacky, but it would certainly speed up the diff retrieval by a large margin.

The other approach would be to revert back to the information gathering process of #3. I. e. cloning the repository in question to some temporary location and to execute a chain of git log commands on the project converting the output to prov vocabulary.

On a personal note, I would prefer to populate the PROV model using only the GitLab API. 
What do you think? Do you have some pointers?

Also, what is the performance expectation for this tool. Is it supposed to finish computation instantly, in seconds, in minutes, in hours? This could also determine the approach taken.

**Comment by caha42** [comment]
My assumption is that we want to do the full population only once. Afterwards we just want to run an update to populate new commits. Therefore time is not the most important factor for the inital population.
But I would wait on @onyame feedback before making a final decision.

**Comment by cdboer** [comment]
Model has been recreated.
