### ISSUE TITLE
Relation 'wasGeneratedBy' for 'tags' incorrect.

### ISSUE THREAD

**Issue by onyame** [DLR-SC/gitlab2prov#51]
In the generated PROV document, the `wasGeneratedBy` relation between `tag_event` Activity and `tag` Entity has wrong direction. In the model file `model.py` its correct.

**Comment by onyame** [comment]
![IMG_0372](https://user-images.githubusercontent.com/499229/122234407-246a0200-cebd-11eb-9529-769e3b55821f.jpeg)

**Comment by cdboer** [comment]
Good find! It was in the wrong direction in `models/__init__.py`
```python
if package.tag_package is not None:
    "..."
    graph.wasGeneratedBy(tag_event.id, tag.id)
   "..."
```
The right direction would be the other way around.
```python
if package.tag_package is not None:
    "..."
    graph.wasGeneratedBy(tag.id, tag_event.id)
   "..."
```
Im going to fix this in the next commit.
