### ISSUE TITLE
Repo documentation needs to be updated ?

### ISSUE THREAD

**Issue by LuigiaCristiano** [DLR-SC/gitlab2prov#82]
I just downloaded the latest version of gitlab2prov  (pip install gitlab2prov) 
and started to play a bit with it
I have the feeling the Documentation available in the repo is not updated..
__________
Command Line Usage from README :

The command line interface consists of commands that can be chained together like a unix pipeline.

Usage: gitlab2prov [OPTIONS] COMMAND1 [ARGS]... [COMMAND2 [ARGS]...]...

  Extract provenance information from GitLab projects.

Options:
  --version        Show the version and exit.
  --verbose        Enable logging to 'gitlab2prov.log'.
  --config FILE    Read config from file.
  --validate FILE  Validate config file and exit.
  --help           Show this message and exit.

Commands:
  combine                  Combine multiple graphs into one.
  extract                  Extract provenance information for one or more...
  load                     Load provenance files.
  merge-duplicated-agents  Merge duplicated agents based on a name to...
  pseudonymize             Pseudonymize a provenance graph.
  save                     Save provenance information to a file.
  stats                    Print statistics such as node counts and...

 
**To Reproduce**
from my command line I type gitlab2prov and I get the following:
gitlab2prov [-h] [-p <string> [<string> ...]] [-t <string>] [-r <int>] [-c <string>] [-f {provn,json,rdf,xml,dot}] [-q] [--aliases <string>] [--pseudonymize]

Extract provenance information from GitLab projects.

optional arguments:
  -h, --help            show this help message and exit
  -p <string> [<string> ...], --project-urls <string> [<string> ...]
                        gitlab project urls
  -t <string>, --token <string>
                        gitlab api access token
  -r <int>, --rate-limit <int>
                        api client rate limit (in req/s)
  -c <string>, --config-file <string>
                        config file path
  -f {provn,json,rdf,xml,dot}, --format {provn,json,rdf,xml,dot}
                        provenance output format
  -q, --quiet           suppress output to stdout
  --aliases <string>    path to agent alias mapping json file
  --pseudonymize        pseudonymize agents

**Comment by cdboer** [comment]
That is weird, it seems that you got an outdated version of gitlab2prov. Could you try to reinstall and force pip to use the most recent version (2.0.0)? I am not able to reproduce your error.

```
pip uninstall gitlab2prov
pip install gitlab2prov==2.0.0
```

**Comment by LuigiaCristiano** [comment]
Thanks,
it worked the way you suggested
