### ISSUE TITLE
Handling commits in the PROV graph

### ISSUE THREAD

**Issue by LuigiaCristiano** [DLR-SC/gitlab2prov#86]
Hi, I do have a question on the usage of the GitLab2PROV.
I make just a generic usage example.
I do have a gitlab repo where I did commits also for small typo correction.
I want to have in my PROV file only "meaningful" commits.
This can be achieved by a proper labeling of the commits.

Can I do explicitate which actions I want to collect in the PROV file at creation time or do I need to select the commits that are relevant for me afterwords?
Do you have a tagging or labeling strategy of gitlab commits that you would suggest to users of your GitLab2PROV package ?
Thanks
Luigia

**Comment by cdboer** [comment]
At the moment no such filtering feature is available. You will have to pick the relevant commits yourself after you generate the PROV file. 

I would suggest to use the python pkg [prov](https://prov.readthedocs.io/en/latest/readme.html) to work with the provenance data. You can filter for entities/activities that represent commits and search for the relevant commit message or sha that you want to keep or delete.

Also, i missed your question in the discussions tab. Good thing that you opened this issue. If you have further questions regarding filtering feel free to ask.
