### ISSUE TITLE
Document licenses of dependencies

### ISSUE THREAD

**Issue by cdboer** [DLR-SC/gitlab2prov#91]
Required Dependencies:
- prov (MIT)
- git-python (BSD 3-Clause)
- python-gitlab (LGPL 3)
- jsonschema (MIT)
- ruamel.yaml (MIT)
- pydot (MIT)
- click (BSD 3-Clause)

Optional Dependencies:
- pytest (MIT)
- pytest-mock (MIT)
- black (MIT)
- isort (MIT)
- bump2version (MIT)

Build Dependencies:
- setuptools (MIT)
- wheel (MIT)

- [x] Choose place for license documentation

**Comment by cdboer** [comment]
@schlauch does it suffice to document the license types of dependencies in `pyproject.toml` or is there a better place to put such information?

**Comment by schlauch** [comment]
A minimum approach would be to list the licenses of the direct main dependencies (you required ones) in the README file.
