### ISSUE TITLE
Update CITATION.cff release date using bump2version

### ISSUE THREAD

**Issue by cdboer** [DLR-SC/gitlab2prov#95]
Related issue, currently unsupported by bump2version:
- https://github.com/c4urself/bump2version/issues/133

**Comment by MattF-NSIDC** [comment]
I am trying to do this for my project, QGreenland, and found your post. I just discovered that this is supported via regex searches in `bump-my-version`, which looks to be bump2version's actively-maintained successor.

https://github.com/callowayproject/bump-my-version/pull/39/files

I'll share our PR implementing this when it's ready.

**Comment by MattF-NSIDC** [comment]
Here's how I got our CITATION.cff to update automatically:

https://github.com/nsidc/qgreenland/commit/79af5756132be49cfabc13291b1c1017dbbfe55a#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R124-R127
